#include <ATen/native/cuda/maca_kernels/Context.h>

namespace at::maca {

#define DEFINE_MACA_CAT_ENV_API(api_name, env_name, defaultValue) \
int api_name() {                                  \
  static char* value = std::getenv(env_name);      \
  if (!value){                                     \
    return defaultValue;                           \
  } else {                                         \
    return std::stoi(value);                     \
  }                                                \
}

#define DEFINE_MACA_ENV_API_NE(api_name, env_name) \
bool api_name() {                                  \
  static char const* temp = std::getenv(env_name); \
  return temp != nullptr;                          \
}

#define DEFINE_MACA_ENV_SHAPE_NE(api_name, env_name)                    \
bool api_name() {                                                       \
  static char const* temp  = std::getenv(env_name);                     \
  static char const* temp1 = std::getenv("PYTORCH_ENABLE_PRINT_INFO");  \
  return temp != nullptr || temp1 != nullptr;                           \
}

#define DEFINE_MACA_ENV_API_E(api_name, env_name)  \
bool api_name() {                                  \
  static char const* temp = std::getenv(env_name); \
  return temp == nullptr;                          \
}

DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_print_nllloss, "PYTORCH_ENABLE_PRINT_NLLLOSS")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_elementwise_multi_outputs_shape, "PYTORCH_ELEMENTWISE_MULTI_OUTPUTS_SHAPE")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_avgpool_backward_info, "PYTORCH_ENABLE_AVGPOOL_BACKWARD_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_gemm_api_info, "PYTORCH_ENABLE_GEMM_API_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_mathlib_api_info , "PYTORCH_ENABLE_MATHLIB_API_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_layernorm_kernel_info, "PYTORCH_ENABLE_LAYERNORM_KERNEL_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_print_batchnorm_info, "PYTORCH_ENABLE_PRINT_BATCHNORM_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_print_conv_info, "PYTORCH_ENABLE_PRINT_CONV_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_print_indexing_info, "PYTORCH_ENABLE_PRINT_INDEXING_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_print_reduce_kernel, "PYTORCH_REDUCE_ENABLE_PRINT")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_print_upsample2d_info, "PYTORCH_ENABLE_PRINT_UPSAMPLE2D_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_print_upsample3d_info, "PYTORCH_ENABLE_PRINT_UPSAMPLE3D_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_print_topk_info, "PYTORCH_ENABLE_PRINT_TOPK_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_print_cat_shape, "PYTORCH_PRINT_CAT_SHAPE")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_print_cub_info, "PYTORCH_PRINT_CUB_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_print_group_norm_shape, "PYTORCH_PRINT_GROUP_NORM_SHAPE")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_print_mha_shape, "PYTORCH_PRINT_MHA_SHAPE")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_print_softmax_shape, "PYTORCH_PRINT_SOFTMAX_SHAPE")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_print_cdist_info, "PYTORCH_ENABLE_PRINT_CDIST_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_elementwise_kernel_info, "PYTORCH_ENABLE_ELEMENTWISE_KERNEL_INFO")
DEFINE_MACA_ENV_SHAPE_NE(get_maca_enable_print_indexing_backward_kernel, "PYTORCH_ENABLE_PRINT_INDEXING_BACKWARD_KERNEL")

DEFINE_MACA_CAT_ENV_API(get_maca_cat_contiguous_batch_threshold, "PYTORCH_CAT_CONTIGUOUS_BATCH_THRESHOLD", 30)
DEFINE_MACA_CAT_ENV_API(get_maca_cat_not_allcontiguous_batch_threshold, "PYTORCH_CAT_NOT_ALLCONTIGUOUS_BATCH_THRESHOLD", 60)
DEFINE_MACA_CAT_ENV_API(get_maca_cat_not_allsamedtype_batch_threshold, "PYTORCH_CAT_NOT_ALLSAMEDTYPE_BATCH_THRESHOLD", 60)
DEFINE_MACA_ENV_API_NE(get_maca_disable_gpu_kernel_with_scalars_arity2, "PYTORCH_DISABLE_GPU_KERNEL_WITH_SCALARS_ARITY2")
DEFINE_MACA_ENV_API_NE(get_maca_enable_same_rand_a100, "PYTORCH_ENABLE_SAME_RAND_A100")
DEFINE_MACA_ENV_API_NE(get_maca_check_anomaly_inf, "PYTORCH_CHECK_ANOMALY_INF")
DEFINE_MACA_ENV_API_NE(get_maca_default_nchw_memory_format, "PYTORCH_DEFAULT_NCHW")
DEFINE_MACA_ENV_API_NE(get_maca_default_ndhwc_memory_format, "PYTORCH_DEFAULT_NDHWC")
DEFINE_MACA_ENV_API_NE(get_maca_default_nlc_memory_format, "PYTORCH_DEFAULT_NLC")
DEFINE_MACA_ENV_API_NE(get_maca_disable_all_to_one_reduce_kernel, "PYTORCH_DISABLE_ALL_TO_ONE_REDUCE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_avgpool_backward_opt, "PYTORCH_DISABLE_AVGPOOL_BACKWARD_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_batch_norm_backward_reduce_channels_last_kernel, "PYTORCH_DISABLE_BATCHNORM_BACKWARD_REDUCE_CHANNELS_LAST_KERNEL")
DEFINE_MACA_ENV_API_NE(get_maca_disable_cat, "PYTORCH_DISABLE_CAT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_continuous_reduce_kernel, "PYTORCH_DISABLE_CONTINUOUS_REDUCE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_continuous_reduce_transpose_kernel, "PYTORCH_DISABLE_CONTINUOUS_REDUCE_TRANSPOSE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_continuous_reduce_kernel_use_offset_calculator, "PYTORCH_DISABLE_CONTINUOUS_REDUCE_USE_OFFSET_CALCULATOR")
DEFINE_MACA_ENV_API_NE(get_maca_disable_cuda_cudnn_tf32, "PYTORCH_DISABLE_CUDA_CUDNN_TF32")
DEFINE_MACA_ENV_API_NE(get_maca_disable_element_template_shape, "PYTORCH_DISABLE_ELEMENT_TEMPLATE_SHAPE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_1_1, "PYTORCH_DISABLE_ELEMENTWISE_1_1")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_1_2_broadcast_kernel, "PYTORCH_DISABLE_ELEMENTWISE_1_2_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_2_2_cast_broadcast_kernel, "PYTORCH_DISABLE_ELEMENTWISE_2_2_CAST_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_2_2_cast_template_kernel, "PYTORCH_DISABLE_ELEMENTWISE_2_2_CAST_TEMPLATE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_1_broadcast_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_1_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_1_copy_opt_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_1_COPY_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_1_dim0_contiguous, "PYTORCH_DISABLE_ELEMENTWISE_3_1_DIM0_CONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_1_transpose_half_copy_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_1_TRANSPOSE_HALF_COPY")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_1_transpose02_half_copy_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_1_TRANSPOSE02_HALF_COPY")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_arity2_transpose_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_ARITY2_TRANSPOSE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_arity2_transpose_dim02_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_ARITY2_TRANSPOSE_DIM02")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_broadcast_arg0_dim2_arg1_dim0_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_BROADCAST_ARG0_DIM2_ARG1_DIM0")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_broadcast_dim1_contiguous_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_BROADCAST_DIM1_CONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_broadcast_dim1_uncontiguous_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_BROADCAST_DIM1_UNCONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_broadcast_dim2_arg0_contiguous_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_BROADCAST_DIM2_ARG0_CONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_broadcast_dim2_contiguous_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_BROADCAST_DIM2_CONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_broadcast_dim2_uncontiguous_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_BROADCAST_DIM2_UNCONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_broadcast_dim0_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_BROADCAST_DIM0")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_dim0_contiguous_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_DIM0_CONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_cast_broadcast_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_CAST_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_cast_broadcast_dim2_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_2_CAST_BROADCAST_DIM2")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_2_dim0_contiguous_arg1_dim1_broadcast_kernel,"PYTORCH_DISABLE_ELEMENTWISE_3_2_DIM0_CONTIGUOUS_ARG1_DIM1_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_3_3_broadcast_kernel, "PYTORCH_DISABLE_ELEMENTWISE_3_3_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_4_1_copy_opt_kernel, "PYTORCH_DISABLE_ELEMENTWISE_4_1_COPY_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_4_1_transpose12_copy_kernel, "PYTORCH_DISABLE_ELEMENTWISE_4_1_TRANSPOSE12_COPY")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_4_2_broadcast_arg0_dim2_arg1_dim0_kernel, "PYTORCH_DISABLE_ELEMENTWISE_4_2_BROADCAST_ARG0_DIM2_ARG1_DIM0")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_4_2_opt_kernel, "PYTORCH_DISABLE_ELEMENTWISE_4_2_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_4_2_template_kernel, "PYTORCH_DISABLE_ELEMENTWISE_4_2_TEMPLATE_KERNEL")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_4_2_uncontiguous_kernel, "PYTORCH_DISABLE_ELEMENTWISE_4_2_UNCONTIGUOUS_KERNEL")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_arity2_cast_unroll, "PYTORCH_DISABLE_ELEMENTWISE_ARITY2_CAST_UNROLL")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_1_1_broadcast, "PYTORCH_DISABLE_ELEMENTWISE_1_1_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_2_1_broadcast, "PYTORCH_DISABLE_ELEMENTWISE_2_1_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_2_1_dim0_contiguous, "PYTORCH_DISABLE_ELEMENTWISE_2_1_DIM0_CONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_2_1_cp_cast_dim0_contiguous, "PYTORCH_DISABLE_ELEMENTWISE_2_1_CP_CAST_DIM0_CONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_2_1_input_lowdim_contiuous, "PYTORCH_DISABLE_ELEMENTWISE_2_1_INPUT_LOWDIM_CONTIUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_2_1_transpose_uncontiguous, "PYTORCH_DISABLE_ELEMENTWISE_2_1_TRANSPOSE_UNCONTIGUSOU")
DEFINE_MACA_ENV_API_NE(get_maca_enable_elementwise_kernel_2_2_align, "PYTORCH_ENABLE_ELEMENTWISE_2_2_ALIGN")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_2_2_arity2_transpose, "PYTORCH_DISABLE_ELEMENTWISE_2_2_ARITY2_TRANPOSE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_2_2_broadcast, "PYTORCH_DISABLE_ELEMENTWISE_2_2_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_2_2_broadcast_arity1_dim0, "PYTORCH_DISABLE_ELEMENTWISE_2_2_BROADCAST_ARITY1_DIM0")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_2_2_template, "PYTORCH_DISABLE_ELEMENTWISE_2_2_TEMPLATE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_4_1_input_lowdim_contiuous, "PYTORCH_DISABLE_ELEMENTWISE_4_1_INPUT_LOWDIM_CONTIUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_4_2_cast_broadcast, "PYTORCH_DISABLE_ELEMENTWISE_4_2_CAST_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_4_2_arg0_dim1_broadcast, "PYTORCH_DISABLE_ELEMENTWISE_4_2_ARG0_DIM1_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_enable_elementwise_kernel_highdim, "PYTORCH_ENABLE_ELEMENTWISE_HIGHDIM")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_multi_outputs, "PYTORCH_DISABLE_ELEMENTWISE_MULTI_OUTPUTS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_fast_fused_dropout_kernel, "PYTORCH_DISABLE_FAST_FUSED_DROPOUT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_expontial_opt, "PYTORCH_DISABLE_EXPONTIAL_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_gatherTopK_opt, "PYTORCH_DISABLE_GATHERTOPK_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_group_norm_backward_opt_kernel, "PYTORCH_DISABLE_GROUP_NORM_BACKWARD_OPT_KERNEL")
DEFINE_MACA_ENV_API_NE(get_maca_disable_group_norm_fused_kernel, "PYTORCH_DISABLE_GROUP_NORM_FUSED_KERNEL")
DEFINE_MACA_ENV_API_NE(get_maca_disable_group_norm_opt_kernel, "PYTORCH_DISABLE_GROUP_NORM_OPT_KERNEL")
DEFINE_MACA_ENV_API_NE(get_maca_disable_imcontinuous_reduce_kernel, "PYTORCH_DISABLE_IMCONTINUOUS_REDUCE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_index_elementwise_1_2_broadcast_kernel, "PYTORCH_DISABLE_INDEX_ELEMENTWISE_1_2_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_disable_max_pool_nhwc_opt, "PYTORCH_DISABLE_MAXPOOL_NHWC_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_mcdnn_bias_fusion, "PYTORCH_DISABLE_MCDNN_BIAS_FUSION")
DEFINE_MACA_ENV_API_NE(get_maca_disable_nllloss_bwd_2d, "PYTORCH_DISABLE_NLLLOSS_BWD_2D")
DEFINE_MACA_ENV_API_NE(get_maca_disable_nllloss_fwd_2d, "PYTORCH_DISABLE_NLLLOSS_FWD_2D")
DEFINE_MACA_ENV_API_NE(get_maca_disable_openblas, "PYTORCH_DISABLE_OPENBLAS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_opt_cat_for_dim5, "PYTORCH_DISABLE_OPT_CAT_FOR_DIM5")
DEFINE_MACA_ENV_API_NE(get_maca_disable_opt_cat_for_not_allcontiguous, "PYTORCH_DISABLE_OPT_CAT_FOR_NOT_ALLCONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_disable_opt_cat_for_not_allsamedtype, "PYTORCH_DISABLE_OPT_CAT_FOR_NOT_ALLSAMETYPE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_opt_indexing, "PYTORCH_DISABLE_OPT_INDEXING")
DEFINE_MACA_ENV_API_NE(get_maca_disable_opt_layernorm_gammabeta, "PYTORCH_DISABLE_OPT_LAYERNORM_GAMMABETA")
DEFINE_MACA_ENV_API_NE(get_maca_disable_opt_layernorm_grad_input, "PYTORCH_DISABLE_OPT_LAYERNORM_GRAD_INPUT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_opt_roll, "PYTORCH_DISABLE_OPT_ROLL")
DEFINE_MACA_ENV_API_NE(get_maca_disable_reduce_split_warp, "PYTORCH_DISABLE_SPLIT_WARP_REDUCE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_scatter_gather_dim2_opt, "PYTORCH_DISABLE_SCATTER_GATHER_DIM2_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_scatter_gather_dim2_opt_assign, "PYTORCH_DISABLE_SCATTER_GATHER_DIM2_OPT_ASSIGN")
DEFINE_MACA_ENV_API_NE(get_maca_disable_scatter_gather_without_assert, "PYTORCH_DISABLE_SCATTER_GATHER_WITHOUT_ASSERT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_sigmoid_opt, "PYTORCH_DISABLE_SIGMOID_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_softmax_backward, "PYTORCH_DISABLE_SOFTMAX_BACKWARD")
DEFINE_MACA_ENV_API_NE(get_maca_disable_softmax_opt, "PYTORCH_DISABLE_SOFTMAX_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_threshold_opt, "PYTORCH_DISABLE_THRESHOLD_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_triu_tril_opt, "PYTORCH_DISABLE_TRIU_TRIL_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_unroll_float_opt, "PYTORCH_DISABLE_UNROLL_FLOAT_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_upsample_bicubic2d_opt, "PYTORCH_DISABLE_UPSAMPLE_BICUBIC2D_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_upsample_trilinear3d_opt, "PYTORCH_DISABLE_UPSAMPLE_TRILINEAR3D_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_vectorized_elementwise_nullary_opt, "PYTORCH_DISABLE_VECTORIZED_ELEMENTWISE_NULLARY_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_vectorized_elementwise_unary_opt, "PYTORCH_DISABLE_VECTORIZED_ELEMENTWISE_UNARY_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_vectorized_layernorm_opt, "PYTORCH_DISABLE_VECTORIZED_LAYERNORM_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_blas_workspace_default_32m, "PYTORCH_DISABLE_BLAS_WORKSPACE_DEFAULT_32M")
DEFINE_MACA_ENV_API_NE(get_maca_enable_conv2d_nhwc, "PYTORCH_ENABLE_CONV2D_NHWC")
DEFINE_MACA_ENV_API_NE(get_maca_enable_conv_nhwc_c_1, "PYTORCH_ENABLE_CONV_NHWC_C_1")
DEFINE_MACA_ENV_API_NE(get_maca_enable_cudnn_depthwise_backend, "PYTORCH_ENABLE_CUDNN_DEPTHWISE_BACKEND")
DEFINE_MACA_ENV_API_NE(get_maca_enable_conv_bf16_enter_origin_logic, "PYTORCH_ENABLE_CONV_BF16_ENTER_ORIGIN_LOGIC")
DEFINE_MACA_ENV_API_NE(get_maca_disable_depwise_conv_opt, "PYTORCH_DISABLE_DEPWISE_CONV_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_enable_cpu_topk_stable_sort, "PYTORCH_ENABLE_CPU_TOPK_STABLE_SORT")
DEFINE_MACA_ENV_API_NE(get_maca_enable_elementwise_kernel_1_1_dilation, "PYTORCH_ENABLE_ELEMENTWISE_1_1_DILATION")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_5_1_lowdim_contiguous, "PYTORCH_DISABLE_ELEMENTWISE_5_1_LOWDIM_CONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_enable_elementwise_kernel_n_1_dim0_pad, "PYTORCH_ENABLE_ELEMENTWISE_N_1_DIM0_PAD")
DEFINE_MACA_ENV_API_NE(get_maca_disable_4_1_dim0_contiguous, "PYTORCH_DISALBE_4_1_DIM0_CONTIGUOUS")
DEFINE_MACA_ENV_API_NE(get_maca_enable_elementwise_without_assert, "PYTORCH_ENABLE_ELEMENTWISE_WITHOUT_ASSERT")
DEFINE_MACA_ENV_API_NE(get_maca_enable_fast_multitensorapply, "PYTORCH_ENABLE_FAST_MULTITENSORAPPLY")
DEFINE_MACA_ENV_API_NE(get_maca_enable_fast_multitensorapply_fused, "PYTORCH_ENABLE_FAST_MULTITENSORAPPLY_FUSED")
DEFINE_MACA_ENV_API_NE(get_maca_enable_geqrf_blas, "PYTORCH_ENABLE_GEQRF_BLAS")
DEFINE_MACA_ENV_API_NE(get_maca_enable_imcontinuous_reduce_kernel_v1, "PYTORCH_ENABLE_IMCONTINUOUS_REDUCE_V1")
DEFINE_MACA_ENV_API_NE(get_maca_enable_indexing_assert_kernel, "PYTORCH_ENABLE_INDEXING_ASSERT")
DEFINE_MACA_ENV_API_NE(get_maca_enable_indexing_backward_kernel_opt, "PYTORCH_ENABLE_INDEXING_BACKWARD_KERNEL_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_indexing_backward_kernel_opt1, "PYTORCH_DISABLE_INDEXING_BACKWARD_KERNEL_OPT1")
DEFINE_MACA_ENV_API_NE(get_maca_enable_memcpy_replace_memset_reduce_kernel, "PYTORCH_REDUCE_ENABLE_MEMCPY_REPLACE_MEMSET")
DEFINE_MACA_ENV_API_NE(get_maca_disable_direct_copy_kernel_replace_memcpy, "PYTORCH_DISABLE_DIRECT_COPY_KERNEL_REPLACE_MEMCPY")
DEFINE_MACA_ENV_API_NE(get_maca_disable_semaphores_reset_reduce_kernel, "PYTORCH_REDUCE_DISABLE_SEMAPHORES_RESET")
DEFINE_MACA_ENV_API_NE(get_maca_enable_mha_fusion, "PYTORCH_ENABLE_MHA_FUSION")
DEFINE_MACA_ENV_API_NE(get_maca_enable_opt_batchnorm_nhwc, "PYTORCH_ENABLE_OPT_BATCHNORM_NHWC")
DEFINE_MACA_ENV_API_NE(get_maca_enable_original_vectorized_layernorm, "PYTORCH_ENABLE_ORIGINAL_VECTORIZED_LAYERNORM")
DEFINE_MACA_ENV_API_NE(get_maca_force_blas_workspace_32m, "PYTORCH_FORCE_BLAS_WORKSPACE_32M")
DEFINE_MACA_ENV_API_NE(get_maca_push_conv_backend_grad_bias_on_cpu, "PYTORCH_ENABLE_PUSH_CONV_BACKEND_GRAD_BIAS_ON_CPU")
DEFINE_MACA_ENV_API_NE(get_maca_disable_element_kernel_opt_tile, "PYTORCH_DISABLE_ELEMENT_KERNEL_OPT_TILE")
DEFINE_MACA_ENV_API_NE(get_maca_disable_element_kernel_cast_opt_tile, "PYTORCH_DISABLE_ELEMENT_KERNEL_CAST_OPT_TILE")
DEFINE_MACA_ENV_API_NE(get_maca_enable_scatter_pw_opt, "PYTORCH_ENABLE_SCATTER_PW_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_alltoall_opt, "PYTORCH_DISABLE_ALLTOALL_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_enable_lstm_cudnn_bf16, "PYTORCH_ENABLE_LSTM_CUDNN_BF16")
DEFINE_MACA_ENV_API_NE(get_maca_enable_cat_contiguous_using_copy, "PYTORCH_ENABLE_CAT_CONTIGUOUS_USING_COPY")
DEFINE_MACA_ENV_API_NE(get_maca_disable_softmax_internal_dim_opt, "PYTORCH_DISABLE_SOFTMAX_INTERNAL_DIM_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_cdist_wave_opt, "PYTORCH_DISABLE_CDIST_WAVE_OPT")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_4_2_arg1_dim3_broadcast, "PYTORCH_DISABLE_ELEMENT_4_2_ARG1_DIM3_BROADCAST")
DEFINE_MACA_ENV_API_NE(get_maca_enable_elementwise_kernel_1_1_cast_dilation, "PYTORCH_ENABLE_ELEMENT_1_1_CAST_DILATION")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_3_2_cast_broadcast_arity2_dim1, "PYTORCH_DISABLE_ELEMENT_3_2_CAST_BROADCAST_ARITY2_DIM1")
DEFINE_MACA_ENV_API_NE(get_maca_disable_elementwise_kernel_cp_4_1_transpose02, "PYTORCH_DISABLE_ELEMENT_CP_4_1_TRANSPOSE02")
DEFINE_MACA_ENV_API_NE(get_maca_enable_fa_cpp_interface, "PYTORCH_ENABLE_FA_CPP_INTERFACE")
DEFINE_MACA_ENV_API_NE(get_maca_enable_fa_input_info, "PYTORCH_ENABLE_FA_INPUT_INFO")

#undef DEFINE_MACA_ENV_API_NE
#undef DEFINE_MACA_ENV_API_E
#undef DEFINE_MACA_CAT_ENV_API

} // at::maca
