#pragma once

#ifdef _WIN32
#define maca_likely(x) (x)
#define maca_unlikely(x) (x)
#else
#define maca_likely(x) __builtin_expect(!!(x), 1)
#define maca_unlikely(x) __builtin_expect(!!(x), 0)
#endif

namespace at::maca {

#define DECLARE_MACA_CAT_ENV_API(name) TORCH_API int name()
#define DECLARE_MACA_ENV_API(name) TORCH_API bool name()
#define DECLARE_MACA_ENV_SHAPE(name) TORCH_API bool name()

DECLARE_MACA_ENV_SHAPE(get_maca_enable_print_nllloss);
DECLARE_MACA_ENV_SHAPE(get_maca_elementwise_multi_outputs_shape);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_avgpool_backward_info);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_gemm_api_info);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_mathlib_api_info);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_layernorm_kernel_info);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_print_batchnorm_info);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_print_conv_info);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_print_indexing_info);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_print_reduce_kernel);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_print_upsample2d_info);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_print_upsample3d_info);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_print_topk_info);
DECLARE_MACA_ENV_SHAPE(get_maca_print_cat_shape);
DECLARE_MACA_ENV_SHAPE(get_maca_print_cub_info);
DECLARE_MACA_ENV_SHAPE(get_maca_print_group_norm_shape);
DECLARE_MACA_ENV_SHAPE(get_maca_print_mha_shape);
DECLARE_MACA_ENV_SHAPE(get_maca_print_softmax_shape);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_print_cdist_info);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_elementwise_kernel_info);
DECLARE_MACA_ENV_SHAPE(get_maca_enable_print_indexing_backward_kernel);

DECLARE_MACA_CAT_ENV_API(get_maca_cat_contiguous_batch_threshold);
DECLARE_MACA_CAT_ENV_API(get_maca_cat_not_allcontiguous_batch_threshold);
DECLARE_MACA_CAT_ENV_API(get_maca_cat_not_allsamedtype_batch_threshold);
DECLARE_MACA_ENV_API(get_maca_disable_gpu_kernel_with_scalars_arity2);
DECLARE_MACA_ENV_API(get_maca_enable_same_rand_a100);
DECLARE_MACA_ENV_API(get_maca_check_anomaly_inf);
DECLARE_MACA_ENV_API(get_maca_default_nchw_memory_format);
DECLARE_MACA_ENV_API(get_maca_default_ndhwc_memory_format);
DECLARE_MACA_ENV_API(get_maca_default_nlc_memory_format);
DECLARE_MACA_ENV_API(get_maca_disable_all_to_one_reduce_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_avgpool_backward_opt);
DECLARE_MACA_ENV_API(get_maca_disable_batch_norm_backward_reduce_channels_last_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_cat);
DECLARE_MACA_ENV_API(get_maca_disable_continuous_reduce_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_continuous_reduce_transpose_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_continuous_reduce_kernel_use_offset_calculator);
DECLARE_MACA_ENV_API(get_maca_disable_cuda_cudnn_tf32);
DECLARE_MACA_ENV_API(get_maca_disable_element_template_shape);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_1_1);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_1_2_broadcast_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_2_2_cast_broadcast_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_2_2_cast_template_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_1_broadcast_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_1_copy_opt_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_1_dim0_contiguous);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_1_transpose_half_copy_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_1_transpose02_half_copy_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_arity2_transpose_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_arity2_transpose_dim02_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_broadcast_arg0_dim2_arg1_dim0_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_broadcast_dim1_contiguous_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_broadcast_dim1_uncontiguous_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_broadcast_dim2_arg0_contiguous_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_broadcast_dim2_contiguous_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_broadcast_dim2_uncontiguous_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_broadcast_dim0_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_dim0_contiguous_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_cast_broadcast_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_cast_broadcast_dim2_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_2_dim0_contiguous_arg1_dim1_broadcast_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_3_3_broadcast_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_4_1_copy_opt_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_4_1_transpose12_copy_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_4_2_broadcast_arg0_dim2_arg1_dim0_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_4_2_opt_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_4_2_template_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_4_2_uncontiguous_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_arity2_cast_unroll);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_1_1_broadcast);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_2_1_broadcast);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_2_1_dim0_contiguous);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_2_1_cp_cast_dim0_contiguous);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_2_1_input_lowdim_contiuous);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_2_1_transpose_uncontiguous);
DECLARE_MACA_ENV_API(get_maca_enable_elementwise_kernel_2_2_align);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_2_2_arity2_transpose);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_2_2_broadcast);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_2_2_broadcast_arity1_dim0);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_2_2_template);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_4_1_input_lowdim_contiuous);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_4_2_cast_broadcast);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_4_2_arg0_dim1_broadcast);
DECLARE_MACA_ENV_API(get_maca_enable_elementwise_kernel_highdim);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_multi_outputs);
DECLARE_MACA_ENV_API(get_maca_disable_expontial_opt);
DECLARE_MACA_ENV_API(get_maca_disable_fast_fused_dropout_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_gatherTopK_opt);
DECLARE_MACA_ENV_API(get_maca_disable_group_norm_backward_opt_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_group_norm_fused_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_group_norm_opt_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_imcontinuous_reduce_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_index_elementwise_1_2_broadcast_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_max_pool_nhwc_opt);
DECLARE_MACA_ENV_API(get_maca_disable_mcdnn_bias_fusion);
DECLARE_MACA_ENV_API(get_maca_disable_nllloss_bwd_2d);
DECLARE_MACA_ENV_API(get_maca_disable_nllloss_fwd_2d);
DECLARE_MACA_ENV_API(get_maca_disable_openblas);
DECLARE_MACA_ENV_API(get_maca_disable_opt_cat_for_dim5);
DECLARE_MACA_ENV_API(get_maca_disable_opt_cat_for_not_allcontiguous);
DECLARE_MACA_ENV_API(get_maca_disable_opt_cat_for_not_allsamedtype);
DECLARE_MACA_ENV_API(get_maca_disable_opt_indexing);
DECLARE_MACA_ENV_API(get_maca_disable_opt_layernorm_gammabeta);
DECLARE_MACA_ENV_API(get_maca_disable_opt_layernorm_grad_input);
DECLARE_MACA_ENV_API(get_maca_disable_opt_roll);
DECLARE_MACA_ENV_API(get_maca_disable_reduce_split_warp);
DECLARE_MACA_ENV_API(get_maca_disable_scatter_gather_dim2_opt);
DECLARE_MACA_ENV_API(get_maca_disable_scatter_gather_dim2_opt_assign);
DECLARE_MACA_ENV_API(get_maca_disable_scatter_gather_without_assert);
DECLARE_MACA_ENV_API(get_maca_disable_sigmoid_opt);
DECLARE_MACA_ENV_API(get_maca_disable_softmax_backward);
DECLARE_MACA_ENV_API(get_maca_disable_softmax_opt);
DECLARE_MACA_ENV_API(get_maca_disable_threshold_opt);
DECLARE_MACA_ENV_API(get_maca_disable_triu_tril_opt);
DECLARE_MACA_ENV_API(get_maca_disable_unroll_float_opt);
DECLARE_MACA_ENV_API(get_maca_disable_upsample_bicubic2d_opt);
DECLARE_MACA_ENV_API(get_maca_disable_upsample_trilinear3d_opt);
DECLARE_MACA_ENV_API(get_maca_disable_vectorized_elementwise_nullary_opt);
DECLARE_MACA_ENV_API(get_maca_disable_vectorized_elementwise_unary_opt);
DECLARE_MACA_ENV_API(get_maca_disable_vectorized_layernorm_opt);
DECLARE_MACA_ENV_API(get_maca_disable_blas_workspace_default_32m);
DECLARE_MACA_ENV_API(get_maca_enable_cudnn_depthwise_backend);
DECLARE_MACA_ENV_API(get_maca_enable_conv_bf16_enter_origin_logic);
DECLARE_MACA_ENV_API(get_maca_disable_depwise_conv_opt);
DECLARE_MACA_ENV_API(get_maca_enable_conv2d_nhwc);
DECLARE_MACA_ENV_API(get_maca_enable_conv_nhwc_c_1);
DECLARE_MACA_ENV_API(get_maca_enable_cpu_topk_stable_sort);
DECLARE_MACA_ENV_API(get_maca_enable_elementwise_kernel_1_1_dilation);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_5_1_lowdim_contiguous);
DECLARE_MACA_ENV_API(get_maca_enable_elementwise_kernel_n_1_dim0_pad);
DECLARE_MACA_ENV_API(get_maca_disable_4_1_dim0_contiguous);
DECLARE_MACA_ENV_API(get_maca_enable_elementwise_without_assert);
DECLARE_MACA_ENV_API(get_maca_enable_fast_multitensorapply);
DECLARE_MACA_ENV_API(get_maca_enable_fast_multitensorapply_fused);
DECLARE_MACA_ENV_API(get_maca_enable_geqrf_blas);
DECLARE_MACA_ENV_API(get_maca_enable_imcontinuous_reduce_kernel_v1);
DECLARE_MACA_ENV_API(get_maca_enable_indexing_assert_kernel);
DECLARE_MACA_ENV_API(get_maca_enable_indexing_backward_kernel_opt);
DECLARE_MACA_ENV_API(get_maca_disable_indexing_backward_kernel_opt1);
DECLARE_MACA_ENV_API(get_maca_enable_memcpy_replace_memset_reduce_kernel);
DECLARE_MACA_ENV_API(get_maca_disable_direct_copy_kernel_replace_memcpy);
DECLARE_MACA_ENV_API(get_maca_disable_semaphores_reset_reduce_kernel);
DECLARE_MACA_ENV_API(get_maca_enable_mha_fusion);
DECLARE_MACA_ENV_API(get_maca_enable_opt_batchnorm_nhwc);
DECLARE_MACA_ENV_API(get_maca_enable_original_vectorized_layernorm);
DECLARE_MACA_ENV_API(get_maca_force_blas_workspace_32m);
DECLARE_MACA_ENV_API(get_maca_push_conv_backend_grad_bias_on_cpu);
DECLARE_MACA_ENV_API(get_maca_disable_element_kernel_opt_tile);
DECLARE_MACA_ENV_API(get_maca_disable_element_kernel_cast_opt_tile);
DECLARE_MACA_ENV_API(get_maca_enable_scatter_pw_opt);
DECLARE_MACA_ENV_API(get_maca_disable_alltoall_opt);
DECLARE_MACA_ENV_API(get_maca_enable_lstm_cudnn_bf16);
DECLARE_MACA_ENV_API(get_maca_enable_cat_contiguous_using_copy);
DECLARE_MACA_ENV_API(get_maca_disable_softmax_internal_dim_opt);
DECLARE_MACA_ENV_API(get_maca_disable_cdist_wave_opt);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_4_2_arg1_dim3_broadcast);
DECLARE_MACA_ENV_API(get_maca_enable_elementwise_kernel_1_1_cast_dilation);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_3_2_cast_broadcast_arity2_dim1);
DECLARE_MACA_ENV_API(get_maca_disable_elementwise_kernel_cp_4_1_transpose02);
DECLARE_MACA_ENV_API(get_maca_enable_fa_cpp_interface);
DECLARE_MACA_ENV_API(get_maca_enable_fa_input_info);

#undef DECLARE_MACA_ENV_API
#undef DECLARE_MACA_CAT_ENV_API

} // at::maca
